FROM python:3.11-slim-bookworm

ENV PYTHONUNBUFFERED=1

WORKDIR /app
COPY . .

RUN --mount=type=cache,target=/root/.cache/pip \
    python -m pip install --editable .

EXPOSE 8000

CMD ["fingraph-dashboard-api", "--host", "0.0.0.0", "--port", "8000"]
