FROM python:3.11-slim-bookworm

ENV PYTHONUNBUFFERED=1

WORKDIR /app
COPY . .

RUN --mount=type=cache,target=/root/.cache/pip \
    python -m pip install --editable .

CMD ["python", "-m", "fingraph.alerting", "--watch"]
